### ISSUE TITLE
Gallery Submission Feedback

### ISSUE THREAD

**Issue by julianhsu8** [data-marketing-school/shopify-checkout-debugger#1]
It appears you have two very similar Pull Requests:

https://github.com/gtm-vendor-templates/template-gallery/pull/1713
https://github.com/gtm-vendor-templates/template-gallery/pull/1714
Can you withdraw one of these two or help us differentiate between these two?

**Comment by lucasgtm** [comment]
I made a mistake when submiting, I first submited a repository on lucasgtm account and then on data-marketing-school account. 

**The right one is on data-marketing-school account.**

Your links end in 404 on my side and I'm don't know how to withdraw it
